#!/bin/bash

IN=(${@})

file_path=${IN[-1]}
file_path_parts=(${file_path//\// })
file_name=${file_path_parts[-1]}
file_name_parts=(${file_name//./ })
script_name=${file_name_parts[-2]}
script_ext=${file_name_parts[-1]}

unset IN[-1]

sbatch \
	--partition=short \
	--nodes=1 \
	--cpus-per-task=1 \
	--job-name=${file} \
	--time=1-00 \
	--mem=4096 \
	--export=NONE \
	--distribution block:block \
	--output=$(pwd)/job_%A_%a.out.log  \
	--error=$(pwd)/job_%A_%a.err.log  \
	${IN[@]} \
	smatlab_script.sh ${file_path} ${script_name}
